dist: disco
install:
- travis_retry sudo apt-get install clang-8 lld-8 gcc-multilib
- travis_retry wget https://sdk.dfinity.org/install.sh
- yes Y | sh install.sh
script:
# Examples in C.
- |
  set -e
  pushd c
  for project in $(ls -d */)
  do 
    pushd $project
    bash build.sh
    popd
  done
  popd
# Examples in Motoko.
- |
  pushd motoko
  for project in $(ls -d */)
  do 
    pushd $project
    make
    popd
  done
  popd
