[package]
name = "exchange_rate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.5.0"
ic-cdk-macros = "0.5.0"
ic-types ="0.3.0"
serde = "1.0.126"
serde_derive = "1.0.126"
chrono = "0.4.19"
cronjob = "0.3.17"
tokio-cron-scheduler = "0.7.0"
queues = "1.1.0"
candid = "0.7.14"
